version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo Installing dependencies (if any)
      # Add install commands here if you have dependencies

  build:
    commands:
      - echo Syncing files to S3 bucket...
      - aws s3 sync . s3://todolatest996144 --exact-timestamps
      - echo Setting public-read ACL for all tracked files...
      - |
        for file in $(git ls-files); do
          aws s3api put-object-acl --bucket todolatest996144 --key "$file" --acl public-read
        done

artifacts:
  files:
    - '**/*'

